### ISSUE TITLE
Hello, what is the reason for this problem during code operation？

### ISSUE THREAD

**Issue by usernameuiui** [SpaceLearner/GNG-ODE#2]
Traceback (most recent call last):
  File "D:/PythonCode/MachineLearning/rs/practice/GNG-ODE-main/main_ode.py", line 31, in <module>
    os.environ["CUDA_VISIBLE_DEVICES"] = str(get_freer_gpu())
  File "D:/PythonCode/MachineLearning/rs/practice/GNG-ODE-main/main_ode.py", line 25, in get_freer_gpu
    memory_available = [int(x.split()[2]) for x in open('tmp', 'r').readlines()]
FileNotFoundError: [Errno 2] No such file or directory: 'tmp'
![image](https://user-images.githubusercontent.com/95755511/222099145-26a51325-a213-48c1-82f8-d0aa29afb466.png)

**Comment by SpaceLearner** [comment]
It may be the GPU driver issue. You can just delete lines 23-31 to ignore the GPU-choosing procedure.
